dbt_bigquery_model:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: house-prediction-381923
      dataset: melbourne_house_data
      location: australia-southeast1
      threads: 4
    
    prod:
      type: bigquery
      method: oauth
      project: house-prediction-381923
      dataset: melbourne_house_data
      location: australia-southeast1
      threads: 1
      timeout_seconds: 300
      retries: 1